# refer: https://bugbyebye.cn/pages/40daf7/

# action workflow 名字 
name: Build xDocs and deploy 
on:
  #监听push操作
  push:
    # main分支，你也可以改成其他分支
    branches: [ main ]

jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: Checkout Branch 'main'
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@v2
      # 安装Node
      - name: Use nodejs v15.4.0
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 15.4.0
      # 安装依赖
      - name: init NPM
        run: npm install
      # 打包
      - name: Build xDocs
        run: npm run build
      # 部署到服务器
      - name: Deploy to server # rsync推文件
        uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ secrets.XDOCS_ACTIONS_SECRET }} # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='*.pyc' # rsync参数，排除.pyc文件
          SERVER_PORT: "22" # SSH端口
          FOLDER: ./docs/.vuepress/dist # 要推送的文件夹，路径相对于代码仓库的根目录，视情况替换为自己的文件夹路径
          SERVER_IP: ${{ secrets.XDOCS_SERVER_IP }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.XDOCS_SERVER_USER }} # 引用配置，服务器登录名
          SERVER_DESTINATION: ${{ secrets.XDOCS_SERVER_DESTINATION }} # 部署到目标文件夹
